import type { Finding, Severity } from "../checks/types.js";
import type { Report, Status } from "../evaluate.js";
import { cell } from "./escape.js";

const STATUS_LABEL: Record<Status, string> = {
  pass: "✅ PASS",
  warn: "⚠️ WARN",
  fail: "❌ FAIL",
  info: "ℹ️ INFO",
  skip: "⏭️ SKIP",
};

const SEVERITY_LABEL: Record<Severity, string> = { error: "❌ error", warn: "⚠️ warn", info: "ℹ️ info" };

export function markdownReporter(report: Report): string {
  const out: string[] = [];
  const { server, target } = report;
  const name = [server.name, server.version].filter(Boolean).join(" ") || "MCP server";
  const where = target.kind === "stdio" ? [target.command, ...target.args].join(" ") : target.url;

  out.push(`# MCP Compatibility Report: ${name}`, "");
  const facts = [
    `Target: \`${where}\``,
    server.protocolVersion
      ? `Protocol ${server.protocolVersion}${server.era === "modern" ? " (stateless only)" : server.era === "both" ? " (also speaks 2026-07-28)" : ""}`
      : undefined,
    server.connected
      ? `${server.counts.tools} tools · ${server.counts.resources} resources · ${server.counts.resourceTemplates} resource templates · ${server.counts.prompts} prompts`
      : "Not connected",
  ].filter(Boolean);
  out.push(facts.join(" · "), "");
  if (server.versions?.length) {
    const cells = server.versions.map(
      (v) => `${v.version} ${!v.ok ? "❌" : v.negotiated && v.negotiated !== v.version ? `↪ ${v.negotiated}` : "✅"}`
    );
    out.push(`Protocol versions: ${cells.join(" · ")}`, "");
  }

  if (report.clients.length > 0) {
    out.push("## Summary", "", "| Client | Pass | Warn | Fail | Info | Skip |", "|---|---|---|---|---|---|");
    for (const c of report.clients) {
      const s = c.summary;
      out.push(`| ${cell(c.displayName)} | ${s.pass} | ${s.warn} | ${s.fail} | ${s.info} | ${s.skip} |`);
    }
    out.push("");
  }

  const general = report.findings.filter((f) => !f.client);
  out.push("## Server issues (all clients)", "");
  if (general.length === 0) {
    out.push("_No client-independent issues found._", "");
  } else {
    out.push(...findingTable(general), "");
  }

  for (const c of report.clients) {
    const rows = c.rows.filter((r) => r.status === "fail" || r.status === "warn" || (r.status === "info" && r.source));
    const clientSpecific = rows.filter((r) => report.findings.some((f) => f.client === c.client && f.checkId === r.checkId));
    const fromGeneral = rows.filter((r) => !clientSpecific.includes(r));
    out.push(`## ${c.displayName}`, "");
    if (clientSpecific.length === 0 && fromGeneral.length === 0) {
      out.push("_No issues specific to this client._", "");
      continue;
    }
    if (clientSpecific.length > 0) {
      out.push("| Status | Check | Subject | Message | Source |", "|---|---|---|---|---|");
      for (const r of clientSpecific) {
        out.push(
          `| ${STATUS_LABEL[r.status]} | \`${r.checkId}\` | ${cell(r.subject)} | ${cell(r.message)} | ${r.source ? `[source](${r.source})` : ""} |`
        );
      }
      out.push("");
    }
    if (fromGeneral.length > 0) {
      const counts = countBy(fromGeneral.map((r) => r.status));
      out.push(`Server issues above affect ${c.displayName}: ${Object.entries(counts).map(([s, n]) => `${n} ${s}`).join(", ")}.`, "");
    }
  }

  const sources = limitationSources(report);
  if (sources.length > 0) {
    out.push("## Client facts referenced", "", ...sources.map((s) => `- ${s}`), "");
  }

  out.push(`<sub>Generated by ${report.tool.name} ${report.tool.version} at ${report.generatedAt}</sub>`, "");
  return out.join("\n");
}

function findingTable(findings: Finding[]): string[] {
  const lines = ["| Severity | Check | Subject | Message | Fix |", "|---|---|---|---|---|"];
  for (const f of findings) {
    lines.push(`| ${SEVERITY_LABEL[f.severity]} | \`${f.checkId}\` | ${cell(f.subject)} | ${cell(f.message)} | ${cell(f.fix)} |`);
  }
  return lines;
}

function limitationSources(report: Report): string[] {
  const seen = new Set<string>();
  for (const c of report.clients) {
    for (const r of c.rows) {
      // Only client-specific facts; general findings' sources would repeat under every client.
      const clientSpecific = report.findings.some((f) => f.client === c.client && f.checkId === r.checkId);
      if (clientSpecific && r.source && (r.status === "warn" || r.status === "fail" || r.status === "info")) {
        seen.add(`${c.displayName}: \`${r.checkId}\`, ${r.source}`);
      }
    }
  }
  return [...seen].sort();
}

function countBy(values: string[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const v of values) counts[v] = (counts[v] ?? 0) + 1;
  return counts;
}
